version: 2

before:
  hooks:
    - go mod download
builds:
  - id: gobl.verifactu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gobl.verifactu
    binary: gobl.verifactu

archives:
  - id: gobl.verifactu
    ids:
      - gobl.verifactu
    formats:
      - tar.gz
    name_template: "gobl.verifactu_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: invopop
    name: gobl.es.verifactu
  prerelease: auto
